package com.cresb.p1archivos.frontend.pantallas.admin;

import com.cresb.p1archivos.backend.database.repository.SucursalRepository;
import com.cresb.p1archivos.backend.jDynamicTable.JDynamicTable;
import com.cresb.p1archivos.backend.jDynamicTable.columns.TextColumnTable;
import com.cresb.p1archivos.backend.models.Sucursal;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author benjamin
 */
public class SeleccionSucursal extends javax.swing.JDialog {
    private final SucursalRepository sucursalRepository = new SucursalRepository();
    private Sucursal sucursal = null;
    private JDynamicTable<Sucursal> dt;
    
    /**
     * Creates new form SeleccionSucursal
     */
    public SeleccionSucursal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.dt = new JDynamicTable<>(this.jTable1,this);
        this.inicializarTabla();
        this.aplicarInformacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SELECCIONAR SUCURSAL");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabla() {
        dt.addColumn(new TextColumnTable("Codigo", "id", true, 50));
        dt.addColumn(new TextColumnTable("Nombre", "nombre", false, 100));
        ButtonSeleccionarSucursal btnSeleccion = new ButtonSeleccionarSucursal("Seleccionar", "Seleccionar", 50);
        dt.addColumn(btnSeleccion);
        dt.apply();
    }

    private void aplicarInformacion() {
        try {
            this.dt.setData(new ArrayList<>(this.sucursalRepository.getAll()));
            this.dt.apply();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public Sucursal getSucursal() {
        return sucursal;
    }

    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
        this.dispose();
    }
}
