/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.cresb.p1archivos.frontend.pantallas.bodega;

import com.cresb.p1archivos.backend.database.repository.BodegaRepository;
import com.cresb.p1archivos.backend.database.repository.ProductoRepository;
import com.cresb.p1archivos.backend.models.Bodega;
import com.cresb.p1archivos.backend.models.Producto;
import java.awt.HeadlessException;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dango
 */
public class AgregarProducto extends javax.swing.JDialog {

    private final ProductoRepository productoRepository = new ProductoRepository();
    private final BodegaRepository bodegaRepository = new BodegaRepository();

    /**
     * Creates new form AgregarProducto
     * @param parent
     * @param modal
     */
    public AgregarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(parent);
        initComponents();
        this.cargarId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldId = new javax.swing.JTextField();
        fieldMarca = new javax.swing.JTextField();
        fieldValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDes = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INGRESAR PRODUCTO");
        setResizable(false);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Descripcion:");

        fieldId.setEditable(false);

        fieldValor.setText("0");

        textDes.setColumns(20);
        textDes.setRows(5);
        jScrollPane1.setViewportView(textDes);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad:");

        jSpinner1.setValue(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNombre)
                            .addComponent(fieldId)
                            .addComponent(fieldMarca)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldValor)
                            .addComponent(jSpinner1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id = this.fieldId.getText();
            String nombre = this.fieldNombre.getText();
            String marca = this.fieldMarca.getText();
            double valor = Double.valueOf(this.fieldValor.getText());
            String des = textDes.getText();
            int cantidad = Integer.parseInt(this.jSpinner1.getValue().toString());

            //Generacion del objeto
            Producto producto = new Producto(id,nombre,marca,valor,des);
            //Asignacion de la existencia en la base de datos
            Bodega bodega = new Bodega(producto,cantidad);

            //Verificacion de la informacion
            this.verificarInformacion(producto,bodega);

            //Registro del producto
            this.productoRepository.guardarProducto(producto);
            //Registro en la bodega
            this.bodegaRepository.save(bodega);

            JOptionPane.showMessageDialog(this, "Se registro con exito el producto", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(this, "No se puede registrar el producto en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }catch (InformacionIncompletaException ex){
            JOptionPane.showMessageDialog(this, "Incosistencia en la informacion asignada:\n"+ex.getMessage(), "Error de campos", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe de agregar un numero en valor y cantidad:\n"+ex.getMessage(), "Error de campos", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verificarInformacion(Producto producto, Bodega bodega) throws InformacionIncompletaException {
        StringBuilder stringBuilder = new StringBuilder();
        if(producto.getId().isBlank()||producto.getId().isEmpty()){
            stringBuilder.append("\t-Se debe de agregar un codigo al producto ejemplo: P000X\n");
        }
        if(producto.getNombre().isBlank()||producto.getNombre().isEmpty()){
            stringBuilder.append("\t-Se debe de agregar nombre al producto\n");
        }
        if(producto.getMarca().isBlank()||producto.getMarca().isEmpty()){
            stringBuilder.append("\t-Se debe de agregar marca al producto\n");
        }
        if(producto.getDescripcion().isBlank()||producto.getDescripcion().isEmpty()){
            stringBuilder.append("\t-Se debe de agregar descripcion al producto\n");
        }
        if(producto.getValor() <= 0){
            stringBuilder.append("\t-El valor del porducto debe de ser mayor o igual a Q. 1.00\n");
        }
        if(bodega.getCantidad()<1){
            stringBuilder.append("\t-La cantidad del producto debe ser mayor o igual a 1\n");
        }
        var result = stringBuilder.toString();
        if(!(result.isEmpty()||result.isBlank())){
            throw  new InformacionIncompletaException(result);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldId;
    private javax.swing.JTextField fieldMarca;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea textDes;
    // End of variables declaration//GEN-END:variables

    private void cargarId() {
        try {
            var id = this.productoRepository.lastId();
            //Eliminamos la P y obtenermos el valro decimal
            int valor = Integer.parseInt(id.substring(1));
            //Generamos el nuevo ID
            String newId = String.format("P%04d", (valor+1));
            this.fieldId.setText(newId);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se puede generar el nuevo ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
